apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-proxy
  # annotations:
  # kubernetes.io/ingress.class: "traefik" # Deprecated
spec:
  ingressClassName: traefik
  rules:
    # No host specified matches all incoming HTTP traffic on port 80
    # If you have a domain, uncomment and update the lines below:
    # Substitua pelo seu domínio real (ex: api.seudominio.com)
    - host: webhook-proxy-prod.heyboy.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhook-proxy
                port:
                  number: 80
