apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webhook-proxy.fullname" . | quote }}
  labels:
    {{- include "webhook-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "webhook-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "webhook-proxy.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8095
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Values.envSecretName | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
